version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: imdb_user
      POSTGRES_PASSWORD: imdb_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/vol/web/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://imdb_user:imdb_pass@db:5432/imdb
      - STATIC_ROOT=/vol/web/static

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_URL=postgres://imdb_user:imdb_pass@db:5432/imdb

volumes:
  postgres_data:
  static_volume:
