FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && mkdir -p /vol/web/static && \
    adduser --disabled-password django-user && \
    chown -R django-user:django-user /vol && \
    chmod -R 755 /vol/web

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY --chown=django-user:django-user . .

# USER django-user

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]